spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/bootcamp_2510p"
    username: "root"
    password: "Admin1234$"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect

mtr:
  data:
    domain: "rt.data.gov.hk"
    path-segment: "v1/transport/mtr/getSchedule.php"
    #     path: "weather.php"
    query: 
       dataType: ""
       lang: "" 
    # or: dataType:
    #          nineday: "fnd"
    #          lang: "en"