spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/bootcamp_2510p"
    username: "root"
    password: "Admin1234$"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect

# Similar to Static Variable in Java
external-api:
  jsonplaceholder:
    domain: "jsonplaceholder.typicode.com"
    paths:
      user-path: "/users"
      post-path: "/posts"
      comment-path: "/comments" # assigment
      # varieble with layers(different subpaths/api)